##elasticsearch cluster yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: poc-elasticsearch
  namespace: elk-cluster
spec:
  version: 7.14.0
  http:
    tls:
      selfSignedCertificate:
        disabled: false
    service:
      spec:
        ports:
        - name: http
          port: 9200
          targetPort: 9200
  nodeSets:
  - name: hot-node-02
    count: 3
      xpack.security.enabled: true
      xpack.security.authc.token.enabled: true
      xpack.security.audit.enabled: true
      node.roles: [ data_hot, master, ingest, remote_cluster_client ]
      xpack:
        security:
          authc:
            realms:
              native:
                native1:
                  enabled: true
                  order: 0
              file:
                file1:
                  enabled: true
                  order: 1

      logger.com.informatica.elastic.xpack.security.ext: DEBUG                 
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8000Mi
              cpu: 2501m
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms4g -Xmx4g"
        imagePullSecrets:
          - name: regcred     
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          securityContext:
            privileged: true
          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-s3']
        tolerations: 
        - effect: NoSchedule
          key: affinity
          value: elastic
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: encrypted-gp2
        resources:
          requests:
            storage: 800Gi

  - name: warm-node-02
    count: 3
    config:
      xpack.security.enabled: true
      xpack.security.authc.token.enabled: true
      xpack.security.audit.enabled: true
      node.roles: [ data_warm, master, ingest, remote_cluster_client ]
      xpack:
        security:
          authc:
            realms:
              native:
                native1:
                  enabled: true
                  order: 0
              file:
                file1:
                  enabled: true
                  order: 1

      logger.com.informatica.elastic.xpack.security.ext: DEBUG                
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4000Mi
              cpu: 1000m
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
        imagePullSecrets:
          - name: regcred       
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          securityContext:
            privileged: true
          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-s3']
        tolerations:
        - effect: NoSchedule
          key: affinity
          value: elastic-warm
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: encrypted-gp2
        resources:
          requests:
            storage: 800Gi

  - name: cold-node-02
    count: 3
    config:
      xpack.security.enabled: true
      xpack.security.authc.token.enabled: true
      xpack.security.audit.enabled: true
      node.roles: [ data_cold, master, ingest, remote_cluster_client ]
      xpack:
        security:
          authc:
            realms:
              native:
                native1:
                  enabled: true
                  order: 0
              file:
                file1:
                  enabled: true
                  order: 1
  
      logger.com.informatica.elastic.xpack.security.ext: DEBUG              
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4000Mi
              cpu: 1000m
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
        imagePullSecrets:
          - name: regcred       
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          securityContext:
            privileged: true
          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-s3']
        tolerations:
        - effect: NoSchedule
          key: affinity
          value: elastic-cold
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: encrypted-gp2
        resources:
          requests:
            storage: 800Gi
